name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Deploy to server
          uses: appleboy/scp-action@v0.1.4
          with: 
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
            source: "."
            target: "~/htdocs/api.6yuwei.com"

        - name: Build
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
            script: |
              export PATH="${{ secrets.SERVER_PATH  }}"
              cd ~/htdocs/api.6yuwei.com
              npm install
              npm run build
            
        - name: Restart PM2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
            script: |
              export PATH="${{ secrets.SERVER_PATH  }}"
              cd ~/htdocs/api.6yuwei.com
              pm2 restart all --update-env